
var textArray = [
    '"AI"',
    '"Altruism"',
    '"Attention"',
    '"Audiovisual"',
    '"Autism"',
    '"Bayesian"',
    '"Behaviour"',
    '"Behavior"',
    '"Bias"',
    '"Connectome"',
    '"Consciousness"',
    '"Cognitive bias"',
    '"Dementia"',
    '"Decision making"',
    '"Development"',
    '"Emotion"',
    '"Executive function"',
    '"Illusion"',
    '"Language"',
    '"Learning"',
    '"Linguistics"',
    '"Memory"',
    '"Metacognition"',
    '"Multisensory"',
    '"Morality"',
    '"Motion"',
    '"Neural network"',
    '"Perception"',
    '"Predictive coding"',
    '"Priming"',
    '"Schizophrenia"',
    '"Social Cognition"',
    '"Speech"',
    '"Spatial memory"',
    '"Theory-of-mind"',
    '"Vision"',
    '"Working memory"'
];
  
module.exports = textArray;

