
var textArray = [
    '"AI"',
    '"Altruism"',
    '"Attention"',
    '"Audiovisual"',
    '"Auditory illusion"',
    '"Autism"',
    '"Awareness"',
    '"Bayesian"',
    '"Behaviour"',
    '"Behavior"',
    '"Bias"',
    '"Connectome"',
    '"Consciousness"',
    '"Cognitive bias"',
    '"Dementia"',
    '"Decision making"',
    '"Development"',
    '"Emotion"',
    '"Executive function"',
    '"Illusion"',
    '"Language"',
    '"Learning"',
    '"Linguistics"',
    '"Memory"',
    '"Metacognition"',
    '"Multisensory"',
    '"Morality"',
    '"Motion"',
    '"Neural network"',
    '"Perception"',
    '"Phi"',
    '"Predictive coding"',
    '"Priming"',
    '"Schizophrenia"',
    '"Social Cognition"',
    '"Speech"',
    '"Spatial memory"',
    '"Theory-of-mind"',
    '"Vision"',
    '"Visual illusion"',
    '"Working memory"'
];
  
module.exports = textArray;

